sonar.verbose=true
sonar.organization=sagar-sonarcube-trend
sonar.projectKey=sagar-sonarcube-trend_sagar-sonar-qube-project01
sonar.projectName=sagar-sonar-qube-project01
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

